---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
    - id: check-executables-have-shebangs
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: trailing-whitespace
