---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
    - id: check-executables-have-shebangs
      name: (files) -- check-executables-have-shebangs
    - id: mixed-line-ending
      name: (code) -- mixed-line-ending
    - id: end-of-file-fixer
      name: (code) -- end-of-line-fixer
    - id: detect-aws-credentials
      name: (security) -- detect-private-key
    - id: detect-private-key
      name: (security) -- detect-private-key
