---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: {{.cluster}}.{{.dnsZone}}
  name: bastion
spec:
  rootVolumeOptimization: {{.bastionRootVolumeOptimization}}
  detailedInstanceMonitoring: {{.bastionDetailedInstanceMonitoring}}
  cloudLabels:
      Environment: {{.cluster}}
      StackName: k8s
  associatePublicIp: {{.bastionAssociatePublicIp}}
  image: {{.bastionImage}}
  machineType: {{.bastionMachineType}}
  rootVolumeSize: {{.bastionRootVolumeSize}}
  rootVolumeType: {{.bastionRootVolumeType}}
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - {{.awsRegion}}a-utility
