---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: {{.cluster}}.{{.dnsZone}}
  name: bastion
spec:
  cloudLabels:
      Environment: {{.cluster}}
      StackName: k8s
  associatePublicIp: true
  image: {{.bastionImage}}
  machineType: {{.bastionMachineType}}
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - {{.awsRegion}}a-utility
