---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: {{.cluster}}.{{.dnsZone}}
  name: master-{{.awsRegion}}c
spec:
  detailedInstanceMonitoring: {{.masterDetailedInstanceMonitoring}}
  cloudLabels:
      Environment: {{.cluster}}
      StackName: k8s
  image: {{.masterImage}}
  machineType: {{.masterMachineType}}
  rootVolumeSize: {{.masterRootVolumeSize}}
  rootVolumeType: {{.masterRootVolumeType}}
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-{{.awsRegion}}c
  role: Master
  subnets:
  - {{.awsRegion}}c-master
