---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: {{.cluster}}.{{.dnsZone}}
  name: master-{{.awsRegion}}a
spec:
  detailedInstanceMonitoring: {{.masterDetailedInstanceMonitoring}}
  cloudLabels:
      Environment: {{.cluster}}
      StackName: k8s
  image: {{.masterImage}}
  machineType: {{.masterMachineType}}
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-{{.awsRegion}}a
  role: Master
  subnets:
  - {{.awsRegion}}a-master
