---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: {{.cluster}}.{{.dnsZone}}
spec:
  api:
    loadBalancer:
      type: {{.apiLoadbalancerType}}
  authorization:
    rbac: {}
  kubelet:
    enableCustomMetrics: {{.kubeletEnableCustomMetrics}}
    cloudProvider: {{.cloudProvider}}
  channel: stable
  cloudProvider: {{.cloudProvider}}
  configBase: s3://{{.configBase}}/{{.cluster}}.{{.dnsZone}}
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-{{.awsRegion}}a
      name: a
      encryptedVolume: {{.etcdEncryptedVolume}}
    - instanceGroup: master-{{.awsRegion}}b
      name: b
      encryptedVolume: {{.etcdEncryptedVolume}}
    - instanceGroup: master-{{.awsRegion}}c
      name: c
      encryptedVolume: {{.etcdEncryptedVolume}}
    enableEtcdTLS: {{.etcdEnableTLS}}
    version: {{.etcdVersion}}
    name: main
  - etcdMembers:
    - instanceGroup: master-{{.awsRegion}}a
      name: a
      encryptedVolume: {{.etcdEncryptedVolume}}
    - instanceGroup: master-{{.awsRegion}}b
      name: b
      encryptedVolume: {{.etcdEncryptedVolume}}
    - instanceGroup: master-{{.awsRegion}}c
      name: c
      encryptedVolume: {{.etcdEncryptedVolume}}
    enableEtcdTLS: {{.etcdEnableTLS}}
    version: {{.etcdVersion}}
    name: events
  iam:
    allowContainerRegistry: {{.iamAllowContainerRegistry}}
    legacy: {{.iamLegacy}}
  kubernetesApiAccess:
  {{range .kubernetesApiAccess}}
    - {{.}}
  {{end}}
  kubernetesVersion: {{.kubernetesVersion}}
  masterPublicName: api.{{.cluster}}.{{.dnsZone}}
  networkCIDR: {{.networkCIDR}}
  networking:
    calico: {}
  nonMasqueradeCIDR: {{.nonMasqueradeCIDR}}
  sshAccess:
  {{range .sshAccess}}
    - {{.}}
  {{end}}
  subnets:
  - cidr: 192.168.0.0/28
    name: {{.awsRegion}}a-node
    zone: {{.awsRegion}}a
    type: Private
  - cidr: 192.168.0.16/28
    name: {{.awsRegion}}b-node
    zone: {{.awsRegion}}b
    type: Private
  - cidr: 192.168.0.32/28
    name: {{.awsRegion}}c-node
    zone: {{.awsRegion}}c
    type: Private
  - cidr: 192.168.0.128/28
    name: {{.awsRegion}}a-utility
    zone: {{.awsRegion}}a
    type: Utility
  - cidr: 192.168.0.144/28
    name: {{.awsRegion}}b-utility
    zone: {{.awsRegion}}b
    type: Utility
  - cidr: 192.168.0.160/28
    name: {{.awsRegion}}c-utility
    zone: {{.awsRegion}}c
    type: Utility
  - cidr: 192.168.0.208/28
    name: {{.awsRegion}}a-master
    zone: {{.awsRegion}}a
    type: Private
  - cidr: 192.168.0.224/28
    name: {{.awsRegion}}b-master
    zone: {{.awsRegion}}b
    type: Private
  - cidr: 192.168.0.240/28
    name: {{.awsRegion}}c-master
    zone: {{.awsRegion}}c
    type: Private
  topology:
    masters: {{.topologyMasters}}
    nodes: {{.topologyNodes}}
    bastion:
      bastionPublicName: bastion.{{.cluster}}.{{.dnsZone}}
    dns:
      type: {{.topologyDnsType}}
